// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ContactsManagerDbContext))]
    [Migration("20260103135725_UpdateUser_StoredProcedure")]
    partial class UpdateUser_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7078c84-62dd-4551-ba74-dad88e597492"),
                            CountryName = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("a055fa40-94c0-43ae-83b0-86138b267297"),
                            CountryName = "India"
                        },
                        new
                        {
                            Id = new Guid("c85c09ff-9da2-44f8-aa86-59502fc3737f"),
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("07481067-c679-4a48-9823-4b04f7e353e0"),
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("fefc9d80-fb10-4114-ac9c-3f0f9e999974"),
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("7da058f2-dfbe-446b-bd9f-c68338399aed"),
                            CountryName = "Srilanka"
                        },
                        new
                        {
                            Id = new Guid("57643ccc-1371-4445-b92c-c74a6e428ed1"),
                            CountryName = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("d12a7f42-8b3e-4f76-9c3b-2f17e0c7a1b5"),
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("e7f2b910-0c4d-4b5a-84d5-3c1f9d2b7e88"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = new Guid("f19a3d2b-6e7c-4f5d-bfa1-8d9c7e1b4a90"),
                            CountryName = "USA"
                        },
                        new
                        {
                            Id = new Guid("a91f3c12-2b8d-4d5e-9f3c-1e2b7c8d9a45"),
                            CountryName = "China"
                        },
                        new
                        {
                            Id = new Guid("c2b1d34f-7a5c-4e6b-b2d3-9f1a7b2c3d4e"),
                            CountryName = "Japan"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("c321d7e8-f400-4cc2-815b-280946a07903"),
                            Address = "Kathmandu",
                            CountryId = new Guid("b7078c84-62dd-4551-ba74-dad88e597492"),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe@email.com",
                            Gender = "Male",
                            PersonName = "John Doe"
                        },
                        new
                        {
                            PersonId = new Guid("072413c7-2185-4e42-8259-823c03697463"),
                            Address = "Delhi",
                            CountryId = new Guid("a055fa40-94c0-43ae-83b0-86138b267297"),
                            DateOfBirth = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anita.sharma@email.com",
                            Gender = "Female",
                            PersonName = "Anita Sharma"
                        },
                        new
                        {
                            PersonId = new Guid("8107934e-75d4-4f75-b630-6b88f6777447"),
                            Address = "Thimphu",
                            CountryId = new Guid("c85c09ff-9da2-44f8-aa86-59502fc3737f"),
                            DateOfBirth = new DateTime(1988, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tenzin.dorji@email.com",
                            Gender = "Male",
                            PersonName = "Tenzin Dorji"
                        },
                        new
                        {
                            PersonId = new Guid("d0a8ee7c-9df4-4277-862e-bf418c953e81"),
                            Address = "Lahore",
                            CountryId = new Guid("07481067-c679-4a48-9823-4b04f7e353e0"),
                            DateOfBirth = new DateTime(1985, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.khan@email.com",
                            Gender = "Male",
                            PersonName = "Ahmed Khan"
                        },
                        new
                        {
                            PersonId = new Guid("cbf1b428-a099-489d-a66a-6023514fa346"),
                            Address = "Dhaka",
                            CountryId = new Guid("fefc9d80-fb10-4114-ac9c-3f0f9e999974"),
                            DateOfBirth = new DateTime(1995, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahima.begum@email.com",
                            Gender = "Female",
                            PersonName = "Rahima Begum"
                        },
                        new
                        {
                            PersonId = new Guid("8e9482b0-4440-45cc-a4bf-641327c40440"),
                            Address = "Colombo",
                            CountryId = new Guid("7da058f2-dfbe-446b-bd9f-c68338399aed"),
                            DateOfBirth = new DateTime(1991, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nimal.perera@email.com",
                            Gender = "Male",
                            PersonName = "Nimal Perera"
                        },
                        new
                        {
                            PersonId = new Guid("a6a41716-c23b-4772-bb40-0da9ad0606e8"),
                            Address = "Male",
                            CountryId = new Guid("57643ccc-1371-4445-b92c-c74a6e428ed1"),
                            DateOfBirth = new DateTime(1993, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aisha.ali@email.com",
                            Gender = "Female",
                            PersonName = "Aisha Ali"
                        },
                        new
                        {
                            PersonId = new Guid("1f2a3b4c-5d6e-7f81-9012-3456789abcde"),
                            Address = "Mumbai",
                            CountryId = new Guid("a055fa40-94c0-43ae-83b0-86138b267297"),
                            DateOfBirth = new DateTime(1989, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rajesh.kumar@email.com",
                            Gender = "Male",
                            PersonName = "Rajesh Kumar"
                        },
                        new
                        {
                            PersonId = new Guid("2b3c4d5e-6f70-8192-0345-6789abcde12f"),
                            Address = "Pokhara",
                            CountryId = new Guid("b7078c84-62dd-4551-ba74-dad88e597492"),
                            DateOfBirth = new DateTime(1994, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sita.lama@email.com",
                            Gender = "Female",
                            PersonName = "Sita Lama"
                        },
                        new
                        {
                            PersonId = new Guid("3c4d5e6f-7081-9234-5678-9abcde123456"),
                            Address = "Karachi",
                            CountryId = new Guid("07481067-c679-4a48-9823-4b04f7e353e0"),
                            DateOfBirth = new DateTime(1987, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "muhammad.ali@email.com",
                            Gender = "Male",
                            PersonName = "Muhammad Ali"
                        },
                        new
                        {
                            PersonId = new Guid("4d5e6f70-8192-3456-789a-bcde12345678"),
                            Address = "Dhaka",
                            CountryId = new Guid("fefc9d80-fb10-4114-ac9c-3f0f9e999974"),
                            DateOfBirth = new DateTime(1996, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.noor@email.com",
                            Gender = "Female",
                            PersonName = "Fatima Noor"
                        },
                        new
                        {
                            PersonId = new Guid("5e6f7081-9234-5678-9abc-de1234567890"),
                            Address = "Galle",
                            CountryId = new Guid("7da058f2-dfbe-446b-bd9f-c68338399aed"),
                            DateOfBirth = new DateTime(1988, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kamal.perera@email.com",
                            Gender = "Male",
                            PersonName = "Kamal Perera"
                        },
                        new
                        {
                            PersonId = new Guid("6f708192-3456-789a-bcde-123456789abc"),
                            Address = "Delhi",
                            CountryId = new Guid("a055fa40-94c0-43ae-83b0-86138b267297"),
                            DateOfBirth = new DateTime(1992, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leela.sharma@email.com",
                            Gender = "Female",
                            PersonName = "Leela Sharma"
                        },
                        new
                        {
                            PersonId = new Guid("70819234-5678-9abc-de12-3456789abcde"),
                            Address = "Paro",
                            CountryId = new Guid("c85c09ff-9da2-44f8-aa86-59502fc3737f"),
                            DateOfBirth = new DateTime(1986, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tashi.wangchuk@email.com",
                            Gender = "Male",
                            PersonName = "Tashi Wangchuk"
                        },
                        new
                        {
                            PersonId = new Guid("81923456-789a-bcde-1234-56789abcdef0"),
                            Address = "Islamabad",
                            CountryId = new Guid("07481067-c679-4a48-9823-4b04f7e353e0"),
                            DateOfBirth = new DateTime(1993, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nadia.khan@email.com",
                            Gender = "Female",
                            PersonName = "Nadia Khan"
                        },
                        new
                        {
                            PersonId = new Guid("92345678-9abc-de12-3456-789abcdef012"),
                            Address = "Lalitpur",
                            CountryId = new Guid("b7078c84-62dd-4551-ba74-dad88e597492"),
                            DateOfBirth = new DateTime(1990, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ramesh.thapa@email.com",
                            Gender = "Male",
                            PersonName = "Ramesh Thapa"
                        },
                        new
                        {
                            PersonId = new Guid("a3456789-abcd-e123-4567-89abcdef0123"),
                            Address = "Mumbai",
                            CountryId = new Guid("a055fa40-94c0-43ae-83b0-86138b267297"),
                            DateOfBirth = new DateTime(1995, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.singh@email.com",
                            Gender = "Female",
                            PersonName = "Priya Singh"
                        },
                        new
                        {
                            PersonId = new Guid("b456789a-bcde-f123-4567-89abcdef0123"),
                            Address = "Thimphu",
                            CountryId = new Guid("c85c09ff-9da2-44f8-aa86-59502fc3737f"),
                            DateOfBirth = new DateTime(1989, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "choden.zangmo@email.com",
                            Gender = "Female",
                            PersonName = "Choden Zangmo"
                        },
                        new
                        {
                            PersonId = new Guid("c56789ab-cdef-1234-5678-9abcdef01234"),
                            Address = "Male",
                            CountryId = new Guid("57643ccc-1371-4445-b92c-c74a6e428ed1"),
                            DateOfBirth = new DateTime(1991, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.faisal@email.com",
                            Gender = "Male",
                            PersonName = "Mohamed Faisal"
                        },
                        new
                        {
                            PersonId = new Guid("d6789abc-def1-2345-6789-abcdef012345"),
                            Address = "Colombo",
                            CountryId = new Guid("7da058f2-dfbe-446b-bd9f-c68338399aed"),
                            DateOfBirth = new DateTime(1994, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.perera@email.com",
                            Gender = "Female",
                            PersonName = "Sara Perera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
